### ISSUE TITLE
Clarify log messages when calendar could not be found

### ISSUE THREAD

**Issue by flix4f** [PTST/O365-HomeAssistant#33]
Error on device update

After first authorization the sensor doesn't get updated.

Log Details (ERROR)
Sat Jan 25 2020 20:47:18 GMT+0100 (Central European Standard Time)
office365calendar: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 299, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/office365calendar/sensor.py", line 248, in update
    self._state = self.device_state_attributes["event_active"]
  File "/config/custom_components/office365calendar/sensor.py", line 143, in device_state_attributes
    query = calendar.new_query("start").greater_equal(start_date)
AttributeError: 'NoneType' object has no attribute 'new_query'
**Installation method (please select one):**

- [X] HACS
- [ ] Manual Installation

Configuration details:
  - platform: office365calendar
    client_id: !secret_clientid
    client_secret: !secret_clientid
    scan_interval: 300
    calendar_name: family room

**Comment by PTST** [comment]
You do not seem to have a calendar called "family room"

**Comment by flix4f** [comment]
Thanks. I am so used to not using Capitals in yaml that I missed that one. Naming is apparently case sensitive.

**Comment by PTST** [comment]
The logs could probably be a bit more clean on this type of error. I will keep this issue open until i fix that

**Comment by PTST** [comment]
Done in v2.0.0
