### ISSUE TITLE
[BUG] Successful setup, but failure to access default_calendar

### ISSUE THREAD

**Issue by cerebrate** [PTST/O365-HomeAssistant#39]
After successful upgrade to latest version (2.1.1), adding necessary permissions in Azure portal, modifying configuration file accordingly -

```
# Office 365 calendar access

o365:
  client_id: !secret o365_client_id
  client_secret: !secret o365_client_secret
  calendars:
    calendar_name: default_calendar
```

- and successfully reauthenticating with Azure, no calendar object appears in Home Assistant. The following error is seen in the log:

```
2020-02-05 11:33:16 ERROR (MainThread) [homeassistant.components.calendar] Error while setting up platform o365
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 158, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/o365/calendar.py", line 39, in setup_platform
    name = calendar.get(CONF_NAME)
AttributeError: 'str' object has no attribute 'get'
```

**Installation method (please select one):**
- [x] HACS
- [ ] Manual Installation

**Comment by PTST** [comment]
The calendars entry should be a list

So
```yaml
o365:
  client_id: !secret o365_client_id
  client_secret: !secret o365_client_secret
  calendars:
    - calendar_name: default_calendar
```

Notice the "-" before the calendar_name

**Comment by PTST** [comment]
I am wondering why the config validation did not catch that, I will keep this issue open until I can check up on this tomorrow.

**Comment by cerebrate** [comment]
*facedesk*

Oops. Thanks.

**Comment by PTST** [comment]
Config validation is now performed correctly in v2.1.2
